/**
 * Business Cards Service
 * AI-powered business card generation for auto shop staff
 */

import { geminiService } from '../../services/gemini.service';
import { imageGenService } from '../../services/image-gen.service';
import { logger } from '../../utils/logger';
import {
  CardStyle,
  CardGenerationInput,
  CardResult,
  CardDesign,
  CARD_STYLES,
  COMMON_TITLES,
  CERTIFICATIONS,
} from './business-cards.types';

class BusinessCardsService {
  /**
   * Get all card styles
   */
  getStyles() {
    return CARD_STYLES;
  }

  /**
   * Get a specific style by ID
   */
  getStyleById(id: CardStyle) {
    return CARD_STYLES.find((s) => s.id === id);
  }

  /**
   * Get common job titles
   */
  getTitles() {
    return COMMON_TITLES;
  }

  /**
   * Get certifications list
   */
  getCertifications() {
    return CERTIFICATIONS;
  }

  /**
   * Generate business card design
   */
  async generateCard(input: CardGenerationInput): Promise<CardResult> {
    const style = this.getStyleById(input.style) || CARD_STYLES[0];

    // Build the image generation prompt
    const prompt = this.buildCardPrompt(input, style);

    // Generate front of card
    const frontImage = await imageGenService.generateImage({
      prompt: prompt.front,
      aspectRatio: input.orientation === 'horizontal' ? '7:4' : '4:7',
      style: 'graphic-design',
    });

    let backImage = null;
    if (input.includeBackDesign) {
      backImage = await imageGenService.generateImage({
        prompt: prompt.back,
        aspectRatio: input.orientation === 'horizontal' ? '7:4' : '4:7',
        style: 'graphic-design',
      });
    }

    // Build design specification
    const design = this.buildDesignSpec(input, style);

    return {
      frontImageUrl: frontImage.url,
      backImageUrl: backImage?.url,
      printReadyPdfUrl: '', // Would be generated by PDF service
      design,
    };
  }

  /**
   * Generate multiple card variations
   */
  async generateVariations(
    input: CardGenerationInput,
    count: number = 3
  ): Promise<Array<{ style: CardStyle; result: CardResult }>> {
    const variations: Array<{ style: CardStyle; result: CardResult }> = [];

    // Select different styles for variations
    const stylesToUse = CARD_STYLES.filter((s) => s.id !== input.style).slice(0, count - 1);
    stylesToUse.unshift(this.getStyleById(input.style) || CARD_STYLES[0]);

    for (const style of stylesToUse.slice(0, count)) {
      const result = await this.generateCard({
        ...input,
        style: style.id,
      });
      variations.push({ style: style.id, result });
    }

    return variations;
  }

  /**
   * Suggest card content based on role
   */
  async suggestContent(title: string, shopName: string): Promise<{
    taglines: string[];
    backContent: string[];
    specialties: string[];
  }> {
    const prompt = `Generate business card content suggestions for an auto repair shop employee.

Role: ${title}
Shop: ${shopName}

Provide:
1. 3 professional taglines for the card (short, memorable)
2. 3 back-of-card content ideas (services, specialties, or shop info)
3. 3-5 relevant specialties based on the role

Format as JSON:
{
  "taglines": ["...", "...", "..."],
  "backContent": ["...", "...", "..."],
  "specialties": ["...", "...", "..."]
}`;

    const response = await geminiService.generateText(prompt);

    try {
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        return JSON.parse(jsonMatch[0]);
      }
    } catch (error) {
      logger.error('Failed to parse content suggestions:', error);
    }

    // Default suggestions
    return {
      taglines: [
        'Your Trusted Auto Care Expert',
        'Quality Service, Fair Prices',
        'Keeping You on the Road',
      ],
      backContent: [
        'Full-service auto repair',
        'ASE Certified Technicians',
        'Family owned since...',
      ],
      specialties: this.getDefaultSpecialties(title),
    };
  }

  /**
   * Build card generation prompt
   */
  private buildCardPrompt(
    input: CardGenerationInput,
    style: typeof CARD_STYLES[0]
  ): { front: string; back: string } {
    const colors = input.customColors || style.colors;
    const orientation = input.orientation === 'horizontal' ? 'landscape' : 'portrait';

    const frontPrompt = `Create a professional business card design for an auto repair shop.

Style: ${style.name} - ${style.description}
Orientation: ${orientation}
Color scheme: Primary ${colors.primary}, Secondary ${colors.secondary}, Accent ${colors.accent}

Card Content:
- Name: ${input.staff.name}
- Title: ${input.staff.title}
- Shop: ${input.shop.name}
${input.shop.tagline ? `- Tagline: ${input.shop.tagline}` : ''}
- Phone: ${input.shop.phone}
${input.staff.email ? `- Email: ${input.staff.email}` : ''}
${input.shop.website ? `- Website: ${input.shop.website}` : ''}
${input.includeQR ? '- Include QR code placeholder in corner' : ''}

Design requirements:
- Clean, professional layout
- ${style.features.join(', ')}
- Typography: ${style.fonts.heading} for headings, ${style.fonts.body} for body
- Include logo placeholder area
- Standard business card proportions
- Print-ready quality
- No bleed artifacts`;

    const backPrompt = `Create the back design for a business card matching the front.

Style: ${style.name}
Orientation: ${orientation}
Color scheme: Primary ${colors.primary}, Secondary ${colors.secondary}

Back content:
- Shop logo (centered or corner)
${input.shop.address ? `- Address: ${input.shop.address}` : ''}
${input.shop.hours ? `- Hours: ${input.shop.hours}` : ''}
${input.staff.certifications?.length ? `- Certifications: ${input.staff.certifications.join(', ')}` : ''}
${input.staff.specialties?.length ? `- Specialties: ${input.staff.specialties.join(', ')}` : ''}

Design requirements:
- Complement the front design
- ${style.features.join(', ')}
- Can be more minimal than front
- Include social media icons if applicable`;

    return { front: frontPrompt, back: backPrompt };
  }

  /**
   * Build design specification for rendering
   */
  private buildDesignSpec(
    input: CardGenerationInput,
    style: typeof CARD_STYLES[0]
  ): CardDesign {
    const isHorizontal = input.orientation === 'horizontal';
    const width = isHorizontal ? 350 : 200;
    const height = isHorizontal ? 200 : 350;

    return {
      front: {
        layout: input.orientation,
        elements: [
          {
            type: 'text',
            content: input.staff.name,
            position: { x: 20, y: isHorizontal ? 60 : 120 },
            style: {
              font: style.fonts.heading,
              fontSize: 24,
              color: style.colors.primary,
              fontWeight: 'bold',
            },
          },
          {
            type: 'text',
            content: input.staff.title,
            position: { x: 20, y: isHorizontal ? 90 : 150 },
            style: {
              font: style.fonts.body,
              fontSize: 14,
              color: style.colors.secondary,
            },
          },
          {
            type: 'logo',
            position: { x: isHorizontal ? width - 100 : 20, y: 20 },
            size: { width: 80, height: 40 },
          },
          {
            type: 'text',
            content: input.shop.phone,
            position: { x: 20, y: height - 50 },
            style: {
              font: style.fonts.body,
              fontSize: 12,
              color: style.colors.text,
            },
          },
          {
            type: 'text',
            content: input.staff.email || '',
            position: { x: 20, y: height - 30 },
            style: {
              font: style.fonts.body,
              fontSize: 11,
              color: style.colors.secondary,
            },
          },
        ],
      },
      back: input.includeBackDesign
        ? {
            layout: input.orientation,
            elements: [
              {
                type: 'logo',
                position: { x: width / 2 - 50, y: 30 },
                size: { width: 100, height: 50 },
              },
              {
                type: 'text',
                content: input.shop.name,
                position: { x: width / 2, y: 100 },
                style: {
                  font: style.fonts.heading,
                  fontSize: 18,
                  color: style.colors.primary,
                  textAlign: 'center',
                },
              },
              {
                type: 'text',
                content: input.shop.tagline || '',
                position: { x: width / 2, y: 125 },
                style: {
                  font: style.fonts.body,
                  fontSize: 12,
                  color: style.colors.secondary,
                  textAlign: 'center',
                },
              },
            ],
          }
        : undefined,
    };
  }

  /**
   * Get default specialties based on title
   */
  private getDefaultSpecialties(title: string): string[] {
    const titleLower = title.toLowerCase();

    if (titleLower.includes('technician') || titleLower.includes('mechanic')) {
      return ['Engine Diagnostics', 'Brake Systems', 'Electrical Repair', 'Preventive Maintenance'];
    }
    if (titleLower.includes('service')) {
      return ['Customer Relations', 'Estimates', 'Scheduling', 'Quality Assurance'];
    }
    if (titleLower.includes('parts')) {
      return ['Parts Sourcing', 'Inventory Management', 'Vendor Relations'];
    }
    if (titleLower.includes('manager') || titleLower.includes('owner')) {
      return ['Business Operations', 'Team Leadership', 'Customer Satisfaction'];
    }

    return ['Auto Repair', 'Customer Service', 'Quality Work'];
  }
}

export const businessCardsService = new BusinessCardsService();
