import { JingleGenre } from './jingle-generator.types';

export const JINGLE_GENRES: JingleGenre[] = [
  {
    id: 'classic-rock',
    name: 'Classic Rock',
    icon: '\uD83C\uDFB8',
    description: 'Energetic guitar riffs and driving drums',
    positiveGlobalStyles: ['classic rock', 'electric guitar', 'energetic', 'catchy hook'],
    negativeGlobalStyles: ['slow', 'ambient', 'electronic', 'hip hop'],
    chorusLocalStyles: ['powerful vocals', 'sing-along chorus', 'guitar riff'],
    introOutroLocalStyles: ['guitar intro', 'rock instrumental'],
  },
  {
    id: 'hip-hop',
    name: 'Hip Hop / Trap',
    icon: '\uD83C\uDFA4',
    description: '808 bass, hi-hats, and swagger',
    positiveGlobalStyles: ['hip hop', 'trap', '808 bass', 'hi-hats', 'catchy'],
    negativeGlobalStyles: ['country', 'acoustic', 'classical', 'jazz'],
    chorusLocalStyles: ['catchy hook', 'rhythmic vocals', 'bass drop'],
    introOutroLocalStyles: ['trap beat', 'bass intro'],
  },
  {
    id: 'country',
    name: 'Country',
    icon: '\uD83E\uDD20',
    description: 'Acoustic guitar and twangy vocals',
    positiveGlobalStyles: ['country', 'acoustic guitar', 'twangy', 'upbeat', 'catchy'],
    negativeGlobalStyles: ['electronic', 'heavy metal', 'rap', 'techno'],
    chorusLocalStyles: ['sing-along chorus', 'country vocals', 'fiddle'],
    introOutroLocalStyles: ['acoustic guitar intro', 'country instrumental'],
  },
  {
    id: 'pop',
    name: 'Pop',
    icon: '\uD83C\uDFB5',
    description: 'Catchy, upbeat, and radio-ready',
    positiveGlobalStyles: ['pop', 'catchy', 'upbeat', 'synthesizers', 'radio-friendly'],
    negativeGlobalStyles: ['heavy metal', 'grunge', 'noise', 'experimental'],
    chorusLocalStyles: ['earworm chorus', 'bright vocals', 'pop hook'],
    introOutroLocalStyles: ['synth intro', 'pop instrumental'],
  },
  {
    id: 'rnb-soul',
    name: 'R&B / Soul',
    icon: '\uD83C\uDFB7',
    description: 'Smooth, groovy, and soulful',
    positiveGlobalStyles: ['r&b', 'soul', 'smooth', 'groovy', 'warm vocals'],
    negativeGlobalStyles: ['heavy metal', 'punk', 'noise', 'harsh'],
    chorusLocalStyles: ['smooth chorus', 'soulful vocals', 'groove'],
    introOutroLocalStyles: ['smooth groove', 'soul instrumental'],
  },
  {
    id: 'reggaeton',
    name: 'Reggaeton',
    icon: '\uD83C\uDF34',
    description: 'Latin beat, catchy, and danceable',
    positiveGlobalStyles: ['reggaeton', 'latin beat', 'catchy', 'danceable', 'dembow'],
    negativeGlobalStyles: ['country', 'classical', 'ambient', 'slow'],
    chorusLocalStyles: ['catchy latin hook', 'rhythmic vocals', 'dembow beat'],
    introOutroLocalStyles: ['latin percussion', 'reggaeton beat intro'],
  },
  {
    id: 'jazz',
    name: 'Jazz',
    icon: '\uD83C\uDFB9',
    description: 'Smooth, sophisticated, and saxophone-driven',
    positiveGlobalStyles: ['jazz', 'smooth', 'saxophone', 'sophisticated', 'swing'],
    negativeGlobalStyles: ['heavy metal', 'electronic', 'punk', 'aggressive'],
    chorusLocalStyles: ['jazz vocals', 'saxophone melody', 'swing rhythm'],
    introOutroLocalStyles: ['jazz piano intro', 'smooth instrumental'],
  },
  {
    id: 'edm',
    name: 'Electronic / EDM',
    icon: '\uD83C\uDFA7',
    description: 'Synthesizers, drops, and dance beats',
    positiveGlobalStyles: ['EDM', 'electronic', 'synthesizers', 'dance beat', 'catchy drop'],
    negativeGlobalStyles: ['acoustic', 'country', 'classical', 'folk'],
    chorusLocalStyles: ['vocal chop', 'drop', 'synth melody', 'dance chorus'],
    introOutroLocalStyles: ['synth build-up', 'electronic intro'],
  },
  {
    id: 'funk',
    name: 'Funk',
    icon: '\uD83D\uDD7A',
    description: 'Bass-heavy, groovy, and feel-good',
    positiveGlobalStyles: ['funk', 'bass-heavy', 'groovy', 'feel-good', 'brass'],
    negativeGlobalStyles: ['ambient', 'classical', 'noise', 'slow'],
    chorusLocalStyles: ['funky vocals', 'bass groove', 'brass stabs'],
    introOutroLocalStyles: ['funk bass intro', 'groove instrumental'],
  },
  {
    id: 'jingle-commercial',
    name: 'Jingle / Commercial',
    icon: '\uD83D\uDCFA',
    description: 'Classic bright, catchy ad jingle style',
    positiveGlobalStyles: ['commercial jingle', 'bright', 'catchy', 'upbeat', 'memorable hook', 'advertising'],
    negativeGlobalStyles: ['dark', 'heavy', 'aggressive', 'sad', 'slow'],
    chorusLocalStyles: ['catchy jingle hook', 'bright vocals', 'ear-catching melody'],
    introOutroLocalStyles: ['bright jingle intro', 'commercial tag'],
  },
];

export function getGenreById(id: string): JingleGenre | undefined {
  return JINGLE_GENRES.find((g) => g.id === id);
}
