import { JingleGenre } from './jingle-generator.types';

export const JINGLE_GENRES: JingleGenre[] = [
  {
    id: 'classic-rock',
    name: 'Classic Rock',
    icon: '\uD83C\uDFB8',
    description: 'Energetic guitar riffs and driving drums',
    positiveGlobalStyles: ['classic rock', 'electric guitar', 'energetic', 'catchy hook'],
    negativeGlobalStyles: ['slow', 'ambient', 'electronic', 'hip hop'],
    chorusLocalStyles: ['powerful vocals', 'sing-along chorus', 'guitar riff'],
    introOutroLocalStyles: ['guitar intro', 'rock instrumental'],
  },
  {
    id: 'hip-hop',
    name: 'Hip Hop / Trap',
    icon: '\uD83C\uDFA4',
    description: '808 bass, hi-hats, and swagger',
    positiveGlobalStyles: ['hip hop', 'trap', '808 bass', 'hi-hats', 'catchy'],
    negativeGlobalStyles: ['country', 'acoustic', 'classical', 'jazz'],
    chorusLocalStyles: ['catchy hook', 'rhythmic vocals', 'bass drop'],
    introOutroLocalStyles: ['trap beat', 'bass intro'],
  },
  {
    id: 'country',
    name: 'Country',
    icon: '\uD83E\uDD20',
    description: 'Acoustic guitar and twangy vocals',
    positiveGlobalStyles: ['country', 'acoustic guitar', 'twangy', 'upbeat', 'catchy'],
    negativeGlobalStyles: ['electronic', 'heavy metal', 'rap', 'techno'],
    chorusLocalStyles: ['sing-along chorus', 'country vocals', 'fiddle'],
    introOutroLocalStyles: ['acoustic guitar intro', 'country instrumental'],
  },
  {
    id: 'pop',
    name: 'Pop',
    icon: '\uD83C\uDFB5',
    description: 'Catchy, upbeat, and radio-ready',
    positiveGlobalStyles: ['pop', 'catchy', 'upbeat', 'synthesizers', 'radio-friendly'],
    negativeGlobalStyles: ['heavy metal', 'grunge', 'noise', 'experimental'],
    chorusLocalStyles: ['earworm chorus', 'bright vocals', 'pop hook'],
    introOutroLocalStyles: ['synth intro', 'pop instrumental'],
  },
  {
    id: 'rnb-soul',
    name: 'R&B / Soul',
    icon: '\uD83C\uDFB7',
    description: 'Smooth, groovy, and soulful',
    positiveGlobalStyles: ['r&b', 'soul', 'smooth', 'groovy', 'warm vocals'],
    negativeGlobalStyles: ['heavy metal', 'punk', 'noise', 'harsh'],
    chorusLocalStyles: ['smooth chorus', 'soulful vocals', 'groove'],
    introOutroLocalStyles: ['smooth groove', 'soul instrumental'],
  },
  {
    id: 'reggaeton',
    name: 'Reggaeton',
    icon: '\uD83C\uDF34',
    description: 'Latin beat, catchy, and danceable',
    positiveGlobalStyles: ['reggaeton', 'latin beat', 'catchy', 'danceable', 'dembow'],
    negativeGlobalStyles: ['country', 'classical', 'ambient', 'slow'],
    chorusLocalStyles: ['catchy latin hook', 'rhythmic vocals', 'dembow beat'],
    introOutroLocalStyles: ['latin percussion', 'reggaeton beat intro'],
  },
  {
    id: 'jazz',
    name: 'Jazz',
    icon: '\uD83C\uDFB9',
    description: 'Smooth, sophisticated, and saxophone-driven',
    positiveGlobalStyles: ['jazz', 'smooth', 'saxophone', 'sophisticated', 'swing'],
    negativeGlobalStyles: ['heavy metal', 'electronic', 'punk', 'aggressive'],
    chorusLocalStyles: ['jazz vocals', 'saxophone melody', 'swing rhythm'],
    introOutroLocalStyles: ['jazz piano intro', 'smooth instrumental'],
  },
  {
    id: 'edm',
    name: 'Electronic / EDM',
    icon: '\uD83C\uDFA7',
    description: 'Synthesizers, drops, and dance beats',
    positiveGlobalStyles: ['EDM', 'electronic', 'synthesizers', 'dance beat', 'catchy drop'],
    negativeGlobalStyles: ['acoustic', 'country', 'classical', 'folk'],
    chorusLocalStyles: ['vocal chop', 'drop', 'synth melody', 'dance chorus'],
    introOutroLocalStyles: ['synth build-up', 'electronic intro'],
  },
  {
    id: 'funk',
    name: 'Funk',
    icon: '\uD83D\uDD7A',
    description: 'Bass-heavy, groovy, and feel-good',
    positiveGlobalStyles: ['funk', 'bass-heavy', 'groovy', 'feel-good', 'brass'],
    negativeGlobalStyles: ['ambient', 'classical', 'noise', 'slow'],
    chorusLocalStyles: ['funky vocals', 'bass groove', 'brass stabs'],
    introOutroLocalStyles: ['funk bass intro', 'groove instrumental'],
  },
  {
    id: 'jingle-commercial',
    name: 'Jingle / Commercial',
    icon: '\uD83D\uDCFA',
    description: 'Classic bright, catchy ad jingle style',
    positiveGlobalStyles: ['commercial jingle', 'bright', 'catchy', 'upbeat', 'memorable hook', 'advertising'],
    negativeGlobalStyles: ['dark', 'heavy', 'aggressive', 'sad', 'slow'],
    chorusLocalStyles: ['catchy jingle hook', 'bright vocals', 'ear-catching melody'],
    introOutroLocalStyles: ['bright jingle intro', 'commercial tag'],
  },
  {
    id: 'latin-pop',
    name: 'Latin Pop',
    icon: '\uD83C\uDF1E',
    description: 'Sunny, rhythmic, and feel-good Latin vibes',
    positiveGlobalStyles: ['latin pop', 'sunny', 'rhythmic', 'feel-good', 'tropical'],
    negativeGlobalStyles: ['heavy metal', 'punk', 'noise', 'dark'],
    chorusLocalStyles: ['catchy latin chorus', 'bright vocals', 'tropical hook'],
    introOutroLocalStyles: ['latin guitar intro', 'tropical percussion'],
  },
  {
    id: 'indie-alt',
    name: 'Indie / Alternative',
    icon: '\u2728',
    description: 'Quirky, authentic indie rock sound',
    positiveGlobalStyles: ['indie rock', 'alternative', 'quirky', 'authentic', 'guitar-driven'],
    negativeGlobalStyles: ['EDM', 'hip hop', 'classical', 'commercial'],
    chorusLocalStyles: ['indie chorus', 'raw vocals', 'jangly guitar'],
    introOutroLocalStyles: ['indie guitar intro', 'lo-fi instrumental'],
  },
  {
    id: 'disco',
    name: 'Disco',
    icon: '\uD83E\uDE69',
    description: 'Groovy 70s dance floor energy',
    positiveGlobalStyles: ['disco', 'groovy', '70s', 'dance floor', 'funky bassline'],
    negativeGlobalStyles: ['heavy metal', 'punk', 'ambient', 'slow'],
    chorusLocalStyles: ['disco chorus', 'falsetto vocals', 'string stabs'],
    introOutroLocalStyles: ['disco strings intro', 'four-on-the-floor beat'],
  },
  {
    id: 'lofi-chill',
    name: 'Lo-fi / Chill',
    icon: '\u2615',
    description: 'Relaxed, mellow beats with warm vibes',
    positiveGlobalStyles: ['lo-fi', 'chill', 'mellow', 'warm', 'relaxed beats'],
    negativeGlobalStyles: ['aggressive', 'heavy metal', 'loud', 'harsh'],
    chorusLocalStyles: ['soft vocals', 'chill melody', 'warm chorus'],
    introOutroLocalStyles: ['lo-fi piano', 'vinyl crackle', 'chill beat intro'],
  },
  {
    id: 'bluegrass',
    name: 'Bluegrass',
    icon: '\uD83C\uDFBB',
    description: 'Fast-picking banjo and fiddle energy',
    positiveGlobalStyles: ['bluegrass', 'banjo', 'fiddle', 'fast-picking', 'acoustic'],
    negativeGlobalStyles: ['electronic', 'hip hop', 'heavy metal', 'techno'],
    chorusLocalStyles: ['bluegrass chorus', 'harmony vocals', 'banjo picking'],
    introOutroLocalStyles: ['banjo intro', 'fiddle instrumental'],
  },
  {
    id: 'metal',
    name: 'Metal / Hard Rock',
    icon: '\uD83E\uDD18',
    description: 'Heavy riffs, power chords, and attitude',
    positiveGlobalStyles: ['metal', 'hard rock', 'heavy riffs', 'power chords', 'aggressive energy'],
    negativeGlobalStyles: ['ambient', 'classical', 'soft', 'lo-fi', 'chill'],
    chorusLocalStyles: ['powerful metal chorus', 'screaming vocals', 'heavy riff'],
    introOutroLocalStyles: ['heavy guitar intro', 'metal instrumental'],
  },
];

export function getGenreById(id: string): JingleGenre | undefined {
  return JINGLE_GENRES.find((g) => g.id === id);
}
