import { PhotoScene, SceneCategory } from './shop-photographer.types';

// ─── Scene Categories ───────────────────────────────────────────────────────

export const SCENE_CATEGORIES: SceneCategory[] = [
  'action-shots',
  'shop-atmosphere',
  'detail-closeups',
  'team-culture',
  'customer-moments',
];

// ─── 25 Scene Templates ────────────────────────────────────────────────────

export const SCENES: PhotoScene[] = [
  // ── Action Shots (6) ──────────────────────────────────────────────────────
  {
    id: 'wrench-turn',
    name: 'Wrench Turn',
    category: 'action-shots',
    shortDescription: 'Mechanic hands turning wrench on engine',
    prompt: 'Close-up of experienced mechanic hands in worn leather work gloves gripping a chrome combination wrench, mid-turn on an engine bolt. Shallow depth of field isolates the hands and wrench against a softly blurred engine bay. Oil-stained fingers show real working hands.',
    suggestedCamera: '85mm f/2.8',
    suggestedLighting: 'Warm tungsten shop overhead mixed with directional fill from portable LED panel camera-left',
    peopleMode: 'partial',
  },
  {
    id: 'brake-inspection',
    name: 'Brake Inspection',
    category: 'action-shots',
    shortDescription: 'Under-lift brake inspection view',
    prompt: 'View from below a hydraulic two-post lift showing a mechanic inspecting brake rotors and calipers. Wide-angle perspective captures the dramatic scale of the car above. Brake dust particles visible in the work light beams.',
    suggestedCamera: '24mm f/4',
    suggestedLighting: 'Undercar portable work lights casting dramatic upward shadows, supplemented by ambient shop fluorescents',
    peopleMode: 'partial',
  },
  {
    id: 'tire-change',
    name: 'Tire Change',
    category: 'action-shots',
    shortDescription: 'Impact gun in action on tire',
    prompt: 'High-speed capture of a pneumatic impact gun in action, lug nuts mid-spin on a wheel hub. Motion blur on the spinning socket while the gun body stays sharp. Compressed air hose trails out of frame. Rubber tire tread fills the background.',
    suggestedCamera: '50mm f/1.8',
    suggestedLighting: 'Strobe freeze at 1/8000s with ambient shop light fill for natural background exposure',
    peopleMode: 'partial',
  },
  {
    id: 'diagnostic-scan',
    name: 'Diagnostic Scan',
    category: 'action-shots',
    shortDescription: 'OBD scanner connected to dashboard',
    prompt: 'An OBD-II diagnostic scanner connected to the port under the dashboard, its screen glowing with live data readouts. The instrument cluster provides ambient dashboard glow in the background. Cable trails from scanner to the diagnostic port.',
    suggestedCamera: '35mm f/2.8',
    suggestedLighting: 'Dashboard instrument glow mixed with warm ambient shop light filtering through the windshield',
    peopleMode: 'none',
  },
  {
    id: 'oil-change-flow',
    name: 'Oil Change Flow',
    category: 'action-shots',
    shortDescription: 'Fresh oil flowing from bottle into engine',
    prompt: 'Golden-amber motor oil pouring from a bottle into an engine oil fill port, viscous stream caught mid-flow with exquisite detail. Light passes through the translucent oil creating a warm amber glow. Oil bottle label slightly out of focus.',
    suggestedCamera: '100mm macro f/2.8',
    suggestedLighting: 'Strong backlight behind the oil stream for amber translucency, soft fill from front to retain detail',
    peopleMode: 'none',
  },
  {
    id: 'under-the-hood',
    name: 'Under the Hood',
    category: 'action-shots',
    shortDescription: 'Silhouette of mechanic leaning into engine bay',
    prompt: 'Dark silhouette of a mechanic leaning into an open engine bay, strong backlight from shop windows creating a dramatic rim-lit outline. Hood prop rod visible. Tools hanging from the fender cover.',
    suggestedCamera: '35mm f/2',
    suggestedLighting: 'Strong backlight rim from bay door or window, no fill — pure silhouette with edge definition',
    peopleMode: 'silhouette',
  },

  // ── Shop Atmosphere (5) ───────────────────────────────────────────────────
  {
    id: 'clean-bay',
    name: 'Clean Bay',
    category: 'shop-atmosphere',
    shortDescription: 'Pristine service bay ready for work',
    prompt: 'An empty, immaculately clean automotive service bay with freshly sealed concrete floor reflecting overhead lights. Two-post lift in center position, tool chest against the wall, air hose reels mounted overhead. The space communicates professional readiness.',
    suggestedCamera: '24mm f/5.6',
    suggestedLighting: 'Overhead fluorescent banks supplemented by natural light from side windows creating mixed color temperature',
    peopleMode: 'none',
  },
  {
    id: 'tool-wall',
    name: 'Tool Wall',
    category: 'shop-atmosphere',
    shortDescription: 'Organized pegboard tool display',
    prompt: 'A meticulously organized pegboard wall displaying chrome wrenches, socket sets, screwdrivers, and specialty tools. Each tool in its designated spot with shadow outlines painted on the board. The organization communicates precision and professionalism.',
    suggestedCamera: '50mm f/4',
    suggestedLighting: 'Even wall-wash lighting from overhead fluorescent strip, slight specular highlights on chrome tool surfaces',
    peopleMode: 'none',
  },
  {
    id: 'car-on-lift',
    name: 'Car on Lift',
    category: 'shop-atmosphere',
    shortDescription: 'Dramatic low-angle of car on lift',
    prompt: 'Dramatic low-angle perspective looking up at a car elevated on a two-post hydraulic lift, undercarriage exposed. The massive scale of the vehicle overhead creates an imposing cinematic composition. Lift arms and safety locks visible.',
    suggestedCamera: '16mm f/8',
    suggestedLighting: 'Cinematic underlighting from work lamps below the car, overhead fluorescents providing rim light on the vehicle body',
    peopleMode: 'none',
  },
  {
    id: 'waiting-room',
    name: 'Waiting Room',
    category: 'shop-atmosphere',
    shortDescription: 'Comfortable clean waiting area',
    prompt: 'A welcoming, spotlessly clean auto shop waiting room with comfortable seating, a coffee station, magazines, and a wall-mounted TV. Large windows let in natural light. The space feels more like a modern lounge than a typical shop waiting area.',
    suggestedCamera: '24mm f/4',
    suggestedLighting: 'Warm natural window light mixed with interior warm-white LED fixtures for an inviting ambiance',
    peopleMode: 'none',
  },
  {
    id: 'shop-front',
    name: 'Shop Front',
    category: 'shop-atmosphere',
    shortDescription: 'Golden hour exterior of shop facade',
    prompt: 'Golden hour exterior photograph of an auto repair shop facade. Warm sunset light bathes the building, signage, and parked vehicles in rich amber tones. Open bay doors reveal the lit interior. Clean parking lot and professional signage.',
    suggestedCamera: '35mm f/5.6',
    suggestedLighting: 'Golden hour natural sunlight with warm color temperature, interior shop lights providing contrast through bay doors',
    peopleMode: 'none',
  },

  // ── Detail Close-ups (5) ──────────────────────────────────────────────────
  {
    id: 'rotor-detail',
    name: 'Rotor Detail',
    category: 'detail-closeups',
    shortDescription: 'Macro shot of machined brake rotor',
    prompt: 'Extreme macro photograph of a freshly machined brake rotor surface showing the concentric machining grooves in polished steel. Raking light reveals the micro-texture of the metal. The rotor vanes visible in shallow depth of field behind the surface.',
    suggestedCamera: '100mm macro f/2.8',
    suggestedLighting: 'Directional raking light from hard source at steep angle to emphasize surface texture and machining marks',
    peopleMode: 'none',
  },
  {
    id: 'spark-plug-array',
    name: 'Spark Plug Array',
    category: 'detail-closeups',
    shortDescription: 'New vs old spark plug comparison',
    prompt: 'Overhead flat-lay of four new iridium spark plugs alongside four worn, carbon-fouled old plugs arranged in a comparison grid on a clean shop rag. The contrast between pristine and spent plugs tells the maintenance story.',
    suggestedCamera: '50mm f/8',
    suggestedLighting: 'Large overhead softbox for even, shadow-free flat-lay illumination with subtle gradient falloff at edges',
    peopleMode: 'none',
  },
  {
    id: 'engine-bay-hero',
    name: 'Engine Bay Hero',
    category: 'detail-closeups',
    shortDescription: 'Magazine-quality engine bay shot',
    prompt: 'Magazine-quality hero photograph of a detailed engine bay — valve cover, intake manifold, hoses, and wiring harness all clean and organized. The engine looks showroom-fresh. Slight depth gradient from front to back of the bay.',
    suggestedCamera: '35mm f/4',
    suggestedLighting: 'Soft diffused overhead light with accent rim lights on chrome and polished surfaces for separation',
    peopleMode: 'none',
  },
  {
    id: 'fresh-tires',
    name: 'Fresh Tires',
    category: 'detail-closeups',
    shortDescription: 'New wheel and tire assembly',
    prompt: 'A brand-new alloy wheel with fresh performance tire, tread nubs still intact, mounted and balanced. Shot at a three-quarter angle showing both the face of the wheel and the tread pattern. Rubber has that factory-fresh sheen.',
    suggestedCamera: '85mm f/4',
    suggestedLighting: 'Studio ring light for even highlight on the wheel face, subtle gradient on the tire sidewall',
    peopleMode: 'none',
  },
  {
    id: 'fluid-check',
    name: 'Fluid Check',
    category: 'detail-closeups',
    shortDescription: 'Backlit dipstick showing clean oil',
    prompt: 'A dipstick held up with clean golden oil at the correct level between the min and max marks. Light transmits through the thin oil film revealing its clarity and color. The engine bay is a soft bokeh background.',
    suggestedCamera: '100mm macro f/2.8',
    suggestedLighting: 'Transmitted backlight through the oil on the dipstick creating a warm amber glow, dark background for contrast',
    peopleMode: 'none',
  },

  // ── Team / Culture (5) ────────────────────────────────────────────────────
  {
    id: 'fist-bump',
    name: 'Fist Bump',
    category: 'team-culture',
    shortDescription: 'Gloved mechanic hands fist bump',
    prompt: 'Two sets of mechanic hands in nitrile work gloves meeting in a fist bump. One pair slightly grease-stained. Shot tight on just the fists with forearms visible. The gesture communicates teamwork and camaraderie.',
    suggestedCamera: '85mm f/2',
    suggestedLighting: 'Warm ambient shop lighting with slight directional fill from overhead fluorescents',
    peopleMode: 'partial',
  },
  {
    id: 'morning-huddle',
    name: 'Morning Huddle',
    category: 'team-culture',
    shortDescription: 'Team shot from behind looking at whiteboard',
    prompt: 'View from behind a group of mechanics in matching uniforms looking at a whiteboard with the daily work schedule. Early morning light streams through the bay door behind them, turning the figures into dramatic silhouettes against bright backlight.',
    suggestedCamera: '24mm f/4',
    suggestedLighting: 'Strong morning light from open bay door creating rim-lit silhouettes, whiteboard is the only front-lit element',
    peopleMode: 'silhouette',
  },
  {
    id: 'tool-handoff',
    name: 'Tool Handoff',
    category: 'team-culture',
    shortDescription: 'One hand passing wrench to another',
    prompt: 'Close-up of one gloved hand passing a ratchet wrench to another waiting hand. The handoff is mid-transfer, both hands visible but no faces. Communicates smooth teamwork and coordination.',
    suggestedCamera: '50mm f/2.8',
    suggestedLighting: 'Focused directional light on the hands and tool, surrounding environment falls to darker tones',
    peopleMode: 'partial',
  },
  {
    id: 'training-moment',
    name: 'Training Moment',
    category: 'team-culture',
    shortDescription: 'Over-shoulder view of technician training',
    prompt: 'Over-the-shoulder perspective of a senior technician pointing at an engine component while training a junior tech. Only the backs of heads, shoulders, and pointing hands are visible. The engine component is in sharp focus.',
    suggestedCamera: '85mm f/2.8',
    suggestedLighting: 'Standard shop overhead lighting with portable work light illuminating the engine component being discussed',
    peopleMode: 'partial',
  },
  {
    id: 'end-of-day',
    name: 'End of Day',
    category: 'team-culture',
    shortDescription: 'Sunset silhouette walking from bay door',
    prompt: 'A single figure in work coveralls walking toward the open bay door at the end of the day. Intense sunset light floods through the opening, turning the person into a complete silhouette. Tool bag in hand. Long shadow stretches across the shop floor.',
    suggestedCamera: '35mm f/5.6',
    suggestedLighting: 'Sunset rim light through bay door, backlit only — complete silhouette with warm orange color cast',
    peopleMode: 'silhouette',
  },

  // ── Customer Moments (4) ──────────────────────────────────────────────────
  {
    id: 'keys-handoff',
    name: 'Keys Handoff',
    category: 'customer-moments',
    shortDescription: 'Hands only — keys handed to customer',
    prompt: 'Close-up of a car key fob being handed from one hand to another across a service counter. One hand wears a clean work glove, the other is a civilian hand. Only hands and forearms visible. The key fob is in crisp focus.',
    suggestedCamera: '85mm f/2',
    suggestedLighting: 'Warm interior front desk lighting, soft and inviting',
    peopleMode: 'partial',
  },
  {
    id: 'thumbs-up',
    name: 'Thumbs Up',
    category: 'customer-moments',
    shortDescription: 'Gloved hand giving thumbs up',
    prompt: 'A single mechanic hand in a blue nitrile glove giving a confident thumbs up. Shot against a blurred shop background with colorful tool chests and equipment. The gesture is enthusiastic and genuine.',
    suggestedCamera: '50mm f/2.8',
    suggestedLighting: 'Bright even shop lighting, clean and optimistic mood',
    peopleMode: 'partial',
  },
  {
    id: 'walk-to-car',
    name: 'Walk to Car',
    category: 'customer-moments',
    shortDescription: 'Customer silhouette walking to car in shop',
    prompt: 'Silhouette of a person walking toward their car inside the service bay. The bay door behind them is wide open with bright daylight streaming in. The car is partially visible, freshly serviced. The walk communicates satisfaction and trust.',
    suggestedCamera: '35mm f/4',
    suggestedLighting: 'Strong backlight from open bay door, figure and car as silhouettes with rim lighting on edges',
    peopleMode: 'silhouette',
  },
  {
    id: 'service-review',
    name: 'Service Review',
    category: 'customer-moments',
    shortDescription: 'Clipboard with service checklist',
    prompt: 'Close-up of a clipboard resting on a service counter with a multi-point inspection checklist. Green check marks fill the boxes. A pen rests across the page. The clipboard is the hero, no people needed.',
    suggestedCamera: '50mm f/4',
    suggestedLighting: 'Warm desk lamp directional light with soft ambient fill from overhead shop lights',
    peopleMode: 'none',
  },
];

// ─── Helpers ────────────────────────────────────────────────────────────────

export function getSceneById(id: string): PhotoScene | undefined {
  return SCENES.find((s) => s.id === id);
}

export function getScenesByCategory(category: string): PhotoScene[] {
  return SCENES.filter((s) => s.category === category);
}
